version: "3.9"
##################################################################
networks:
  dockernet:
    name: "dockernet"
    external: true
  paperlessnet:
    name: "paperlessnet"

##################################################################
secrets:
  #----------------------------------------------------#
  IONOS_API_KEY:
    file: "./secrets/ionos_api_key"
  #----------------------------------------------------#
  bitwarden_admin_token:
    file: "./secrets/bitwarden_admin_token"
  bitwarden_smtp_host:
    file: "./secrets/smtp_host"
  bitwarden_smtp_user:
    file: "./secrets/smtp_user"
  bitwarden_smtp_password:
    file: "./secrets/smtp_password"
  #----------------------------------------------------#
  paperless_db_name:
    file: "./secrets/paperless_db_name"
  paperless_db_user:
    file: "./secrets/paperless_db_user"
  paperless_db_password:
    file: "./secrets/paperless_db_password"
  #----------------------------------------------------#

##################################################################
services:
  traefik:
    image: "traefik:latest"
    container_name: "traefik"
    hostname: "traefik"
    restart: "unless-stopped"
    command:
      - "--log.level=Error"
      - "--api.insecure=true"
      ### docker provider ###
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--providers.docker.watch=true"
      - "--providers.docker.endpoint=unix:///var/run/docker.sock"
      - "--providers.docker.network=dockernet"
      ### entrypoints ###
      - "--entrypoints.web.address=:80"
      - "--entrypoints.web.http.redirections.entryPoint.to=websecure"
      - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
      - "--entrypoints.websecure.address=:443"
      - "--entrypoints.websecure.http.tls=true"
      - "--entrypoints.websecure.http.tls.certResolver=leresolver"
      - "--entrypoints.websecure.http.tls.domains[0].main=${domain}"
      - "--entrypoints.websecure.http.tls.domains[0].sans=*.${domain}"
      ### certificateresolvers ###
      - "--certificatesresolvers.leresolver.acme.dnschallenge.provider=ionos"
      - "--certificatesresolvers.leresolver.acme.dnschallenge.delaybeforecheck=0"
      - "--certificatesresolvers.leresolver.acme.dnschallenge.resolvers=1.1.1.1:53,1.0.0.1:53"
      - "--certificatesresolvers.leresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory" # testing
      - "--certificatesresolvers.leresolver.acme.email=${le_mail}"
      - "--certificatesresolvers.leresolver.acme.storage=/letsencrypt/acme.json"
      - "--certificatesresolvers.leresolver.acme.keytype=RSA4096"
    environment:
      - "IONOS_API_KEY_FILE=/run/secrets/IONOS_API_KEY"
    secrets:
      - "IONOS_API_KEY"
    ports:
      - "80:80"
      - "443:443"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.traefik.rule=Host(\"traefik.${domain}\")"
      - "traefik.http.services.traefik.loadbalancer.server.port=8080"
      - "traefik.http.routers.traefik.entrypoints=websecure"
    volumes:
      - "./data/traefik/letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
      - "./data/traefik/rules:/rules"
      - "./data/traefik/traefik.log:/traefik.log"
      - "./data/traefik/shared:/shared"
    networks:
      dockernet:
        ipv4_address: 172.18.0.2
    dns:
      - "10.0.0.254"
  portainer:
    image: "portainer/portainer-ce:latest"
    container_name: "portainer"
    hostname: "portainer"
    restart: "unless-stopped"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./data/portainer:/data"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.portainer.rule=Host(\"portainer.${domain}\")"
      - "traefik.http.services.portainer.loadbalancer.server.port=9000"
      - "traefik.http.routers.portainer.entrypoints=websecure"
    networks:
      dockernet:
        ipv4_address: 172.18.0.3
    dns:
      - "10.0.0.254"
  bitwarden:
    image: "vaultwarden/server:latest"
    container_name: "bitwarden"
    hostname: "bitwarden"
    restart: "unless-stopped"
    volumes:
       - "./data/bitwarden:/data"
    secrets:
      - "bitwarden_admin_token"
      - "bitwarden_smtp_user"
      - "bitwarden_smtp_password"
      - "bitwarden_smtp_host"
    environment:
      - "ADMIN_TOKEN_FILE=/run/secrets/bitwarden_admin_token"
      - "WEBSOCKET_ENABLED=true"
      - "SIGNUPS_ALLOWED=false"
      - "SMTP_HOST_FILE=/run/secrets/bitwarden_smtp_host"
      - "SMTP_FROM_FILE=/run/secrets/bitwarden_smtp_user"
      - "SMTP_PORT=587"
      - "SMTP_SSL=True"
      - "SMTP_USERNAME_FILE=/run/secrets/bitwarden_smtp_user"
      - "SMTP_PASSWORD_FILE=/run/secrets/bitwarden_smtp_password"
      - "DOMAIN=https://bitwarden.${domain}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.bitwarden.loadbalancer.server.port=80"
      - "traefik.http.routers.bitwarden.rule=Host(\"bitwarden.${domain}\")"
      - "traefik.http.routers.bitwarden.entrypoints=websecure"
    networks:
      dockernet:
        ipv4_address: 172.18.0.4
    dns:
      - "10.0.0.254"
  checkmk:
    image: "checkmk/${checkmk_edition}:${checkmk_version}"
    container_name: "checkmk"
    hostname: "checkmk"
    restart: "unless-stopped"
    ports:
      - "6557:6557"
    tmpfs:
      - "/opt/omd/sites/cmk/tmp:uid=1000,gid=1000"
    volumes:
       - "./data/checkmk:/omd/sites"
       - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.checkmk.loadbalancer.server.port=5000"
      - "traefik.http.routers.checkmk.rule=Host(\"checkmk.${domain}\")"
      - "traefik.http.routers.checkmk.entrypoints=websecure"
    networks:
      dockernet:
        ipv4_address: 172.18.0.5
    dns:
      - "10.0.0.254"
  speedtest:
    image: "henrywhitaker3/speedtest-tracker"
    container_name: "speedtest"
    hostname: "speedtest"
    restart: "unless-stopped"
    volumes:
      - "./data/speedtest:/config"
    environment:
      - "TZ=Europe/Berlin"
      - "OOKLA_EULA_GDPR=true"
    logging:
      driver: "json-file"
      options:
        max-file: "10"
        max-size: "200k"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.speedtest.loadbalancer.server.port=80"
      - "traefik.http.routers.speedtest.rule=Host(\"speedtest.${domain}\")"
      - "traefik.http.routers.speedtest.entrypoints=websecure"
    networks:
      dockernet:
        ipv4_address: 172.18.0.6
    dns:
      - "10.0.0.254"
  paperless-broker:
    image: redis:6.0
    container_name: paperless-broker
    hostname: paperless-broker
    restart: unless-stopped
    volumes:
      - ./data/paperless/broker-data:/data
    networks:
      paperlessnet:
    dns:
      - "10.0.0.254"
  paperless-db:
    image: postgres:13
    container_name: paperless-db
    hostname: paperless-db
    restart: unless-stopped
    volumes:
      - ./data/paperless/db-data:/var/lib/postgresql/data
    # secrets:
    #   - "paperless_db_user"
    #   - "paperless_db_password"
    environment:
      # - "POSTGRES_USER_FILE=/run/secrets/paperless_db_user"
      # - "POSTGRES_PASSWORD_FILE=/run/secrets/paperless_db_password"
      POSTGRES_DB: paperless
      POSTGRES_USER: paperless
      POSTGRES_PASSWORD: paperless
    networks:
      paperlessnet:
    dns:
      - "10.0.0.254"
  paperless-webserver:
    image: ghcr.io/paperless-ngx/paperless-ngx:latest
    container_name: paperless-webserver
    hostname: paperless-webserver
    restart: unless-stopped
    depends_on:
      - paperless-broker
      - paperless-db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8000"]
      interval: 30s
      timeout: 10s
      retries: 5
    volumes:
      - ./data/paperless/webserver-data:/usr/src/paperless/data
      - ./data/paperless/webserver-media:/usr/src/paperless/media
      - ./data/paperless/webserver-export:/usr/src/paperless/export
      - ./data/paperless/webserver-consume:/usr/src/paperless/consume
    # secrets:
    #   - "paperless_db_user"
    #   - "paperless_db_password"
    environment:
      PAPERLESS_REDIS: redis://paperless-broker:6379
      PAPERLESS_DBHOST: paperless-db
      # - "PAPERLESS_DBNAME_FILE=/run/secrets/paperless_db_user"
      # - "PAPERLESS_DBUSER_FILE=/run/secrets/paperless_db_user"
      # - "PAPERLESS_DBPASS_FILE=/run/secrets/paperless_db_password"
      PAPERLESS_TIME_ZONE: Europe/Berlin
      PAPERLESS_OCR_LANGUAGE: deu
      PAPERLESS_FILENAME_FORMAT: "{created_year}/{correspondent}/{asn}-{title}"
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.paperless-webserver.loadbalancer.server.port=8000"
      - "traefik.http.routers.paperless-webserver.rule=Host(\"paperless.${domain}\")"
      - "traefik.http.routers.paperless-webserver.entrypoints=websecure"
    networks:
      paperlessnet:
      dockernet:
        ipv4_address: 172.18.0.7
    dns:
      - "10.0.0.254"