version: "3.9"
##################################################################
networks:
  proxynet:
    name: proxynet
    external: true

##################################################################
services:
  wordpress1:
    image: wordpress
    container_name: 'wordpress1'
    hostname: 'wordpress1'
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
     - WORDPRESS_DB_USER=root
    volumes:
     - ./html:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress1.rule=Host(\"wordpress1.${DOMAIN}\")"
      - "traefik.http.services.wordpress1.loadbalancer.server.port=80"
      - "traefik.http.routers.wordpress1.entrypoints=websecure"
    networks:
      proxynet:
    dns:
      - "172.18.0.5"
  mariadb1:
    image: mariadb
    container_name: 'mariadb1'
    hostname: 'mariadb1'
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql
    networks:
      proxynet:
    dns:
      - "172.18.0.5"

  wordpress2:
    image: wordpress
    container_name: 'wordpress2'
    hostname: 'wordpress2'
    links:
     - mariadb:mysql
    environment:
     - WORDPRESS_DB_PASSWORD=password
     - WORDPRESS_DB_USER=root
    ports:
     - "public_ip:80:80"
    volumes:
     - ./html:/var/www/html
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.wordpress2.rule=Host(\"wordpress2.${DOMAIN}\")"
      - "traefik.http.services.wordpress2.loadbalancer.server.port=80"
      - "traefik.http.routers.wordpress2.entrypoints=websecure"
    networks:
      proxynet:
    dns:
      - "172.18.0.5"
  mariadb2:
    image: mariadb
    container_name: 'mariadb2'
    hostname: 'mariadb2'
    environment:
     - MYSQL_ROOT_PASSWORD=password
     - MYSQL_DATABASE=wordpress
    volumes:
     - ./database:/var/lib/mysql
    networks:
      proxynet:
    dns:
      - "172.18.0.5"